"""initial

Revision ID: 1c4a6e0040e6
Revises: 
Create Date: 2026-05-17 15:31:34.530270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4a6e0040e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_symbol'), 'alert_events', ['symbol'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_symbol'), 'alert_rules', ['symbol'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('news_sentiment_score', sa.Float(), nullable=False),
    sa.Column('fundamental_score', sa.Float(), nullable=False),
    sa.Column('macro_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('stance', sa.String(length=20), nullable=False),
    sa.Column('thesis', sa.String(length=10000), nullable=False),
    sa.Column('bull_case', sa.String(length=5000), nullable=False),
    sa.Column('base_case', sa.String(length=5000), nullable=False),
    sa.Column('bear_case', sa.String(length=5000), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('input_snapshot', sa.String(length=10000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_symbol'), 'analyses', ['symbol'], unique=False)
    op.create_table('company_info',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=5000), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_symbol'), 'news_articles', ['symbol'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_symbol'), 'price_history', ['symbol'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change_percent', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_symbol'), 'price_snapshots', ['symbol'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('signal_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('stance', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('price_at_analysis', sa.Float(), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('price_at_check', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_outcomes_symbol'), 'signal_outcomes', ['symbol'], unique=False)
    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_entries_symbol'), 'watchlist_entries', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_entries_symbol'), table_name='watchlist_entries')
    op.drop_table('watchlist_entries')
    op.drop_index(op.f('ix_signal_outcomes_symbol'), table_name='signal_outcomes')
    op.drop_table('signal_outcomes')
    op.drop_table('settings')
    op.drop_index(op.f('ix_price_snapshots_symbol'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_price_history_symbol'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_news_articles_symbol'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('company_info')
    op.drop_index(op.f('ix_analyses_symbol'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_alert_rules_symbol'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_alert_events_symbol'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
